### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by nschucky** [marmelroy/Interpolate#11]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by GoldenJoe** [comment]
Anybody ever come up with a fix for Swift3?

**Comment by marmelroy** [comment]
Thanks @nschucky and @GoldenJoe! 

Since Swift 3.0 is not fully implemented on Apple's side, I have decided to wait a little before starting a Swift 3.0 branch. Hope that's okay.
