### ISSUE TITLE
Interpolate not running with Double values

### ISSUE THREAD

**Issue by wafisher** [marmelroy/Interpolate#15]
For some reason, the following doesn't work at all:

    let i = Interpolate(from: 100.0, to: 3.0, apply: { n in print(n) })
    i.animate(duration: 3.0)

but this does:

    i = Interpolate(from: CGFloat(100.0), to: CGFloat(3.0), apply: { n in print(n) })
    i.animate(duration: 3.0)

I'm using version 0.2.0 with Swift 2.3. I can't figure this out without getting pretty deep into the code but the `init()` _seems_ to set up the instance variables identically. I'm lost, but I'd love to know what the problem is — hopefully on my end.

**Comment by marmelroy** [comment]
Hey @wafisher! 

Indeed, there was a bug there. Thank you so much for reporting it.

I just pushed a fix and bundled it as release 0.3.1 (it's a Swift 3.0 release but the bug and the fix are the same in Swift 2.3). I also added a test to prevent it from reappearing in the future.

**Comment by wafisher** [comment]
Awesome, thanks for the quick turnaround!
