### ISSUE TITLE
SpringInterpolation does not complete

### ISSUE THREAD

**Issue by otymartin** [marmelroy/Interpolate#21]
@marmelroy 
eg. `SpringInterpolation(damping: 30.0, velocity: 0.0, mass: 1.0, stiffness: 100.0)`
Hey, I find that using Spring Interpolations, my animations do not finish at their  destination even though progress = 100%. Instead they are always near completion.

Why is that?

**Comment by luckysmg** [comment]
Same problem, any way to solve? @otymartin
