### ISSUE TITLE
Mid Vector

### ISSUE THREAD

**Issue by bryan1anderson** [marmelroy/Interpolate#5]
I was hoping Interpolate could make my life a lot easier with my current task.
I have 3 screens inside a UIScrollView
So three pages.
Each pages is a specific color.
I need to animate the background color as I scroll.
It seems that interpolate only allows two vectors. To and From
I need to define a third: Mid.
So if `progress` was at 0 then the screen would be blue.
`progress` was set to 0.5 the screen would be red
`progress` set to 1 would be green.

Is this possible with the current version?

**Comment by marmelroy** [comment]
Hey Brian!

You could get the behaviour that you want with the current version by using two interpolations but I agree that a CAKeyframeAnimation-equivalent API for Interpolate would be useful. Something to consider for the next version...

**Comment by bryan1anderson** [comment]
@marmelroy 
Thanks for the quick response! I had to think about your suggestion for a minute.. haha its been a long day. But I figured it out. Thanks! Very very awesome tool. One of the best written libraries I've seen.

**Comment by marmelroy** [comment]
Hi @bryan1anderson, just wanted to say that this was added in release 0.2.0. Thanks again for the request.
