### ISSUE TITLE
start multiple animations at the same time

### ISSUE THREAD

**Issue by tcurdt** [marmelroy/Interpolate#9]
The example app has basically

```
    func progress(scrollProgress:CGFloat) {
        let groundProgress = scrollProgress * 1.5
        backgroundColorChange?.progress = scrollProgress
        logoAlpha?.progress = scrollProgress
        groundPosition?.progress = groundProgress
        bojackPosition?.progress = groundProgress
        bojackShadowPosition?.progress = max(groundProgress - 1, 0)
    }
```

So I can set the progress with `procress(0)` and `procress(1)` for the whole interpolations - but how I can animate that? Running `animate` on all interpolations feels wrong. Something along the lines of this would be great:

```
progress(0)
UIView.animate(...) {
  progress(1)
}
```

**Comment by marmelroy** [comment]
As mentioned in the README. The scrollProgress function is for times when you want the animation progress to be tied to a gesture/function that reports every step of its progress.

To animate from 0 to 1, every Interpolate object has an animate function. So you would do:
```        
backgroundColorChange?.animate(duration: 0.3)
```
